name: Create

on:
  workflow_dispatch:

jobs:
  mist-download:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install mist-cli
        run: |
          brew install mist-cli

      - name: List available macOS installers
        run: |
          mist list installer --include-betas