name: Download macOS Installer with Mist CLI

on:
  workflow_dispatch:

jobs:
  mist-download:
    runs-on: macos-15
    steps:
      - name: Checkout (required even if empty)
        uses: actions/checkout@v4

      - name: Install mist-cli
        run: |
          brew tap ninxsoft/mist
          brew install mist-cli

      - name: List available macOS installers
        run: |
          mist list installer --include-betas